#ey

name: ci

on:
  push:
    branches:
      - "main"

jobs:

  build:

    runs-on: self-hosted



    steps:
#      - run: ping -c 4 192.168.0.222
#      - run: 
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
     - name: Checkout code
        uses: actions/checkout@v3

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

